### ISSUE TITLE
Chore: Release new version of fields package

### ISSUE THREAD

**Issue by jtsmills** [dwyl/fields#157]
Hey folks, it's been over a year since the last release and there have been a number of dependency upgrades thanks to Dependabot (especially `argon2_elixir ~> 4.0.0`). I would really appreciate if we could cut a new release. 😄 Happy to help.

**Comment by jtsmills** [comment]
@nelsonic is there anything that I can do or open a PR for?

**Comment by jtsmills** [comment]
@nelsonic friendly nudge. :)

**Comment by nelsonic** [comment]
@jtsmills thanks for the nudge. 😉 
Apologies for delay. ⏳ 🤦‍♂️ 
Package published to https://hex.pm/packages/fields/2.11.0 📦 🚀 

PR: https://github.com/dwyl/fields/pull/160 🧑‍💻 (for future ref)
You're invited to be a collaborator on the package. 📥  https://github.com/dwyl/fields/invitations 🔗

**Comment by jtsmills** [comment]
Thank you! :)
