### ISSUE TITLE
Data Sanitisation Helpers

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#19]
As a Developer, I need helper functions for ***sanitising*** data before it gets encrypted and stored 
to _avoid_ **Cross Site Scripting** (XSS) and other malicious attacks on the web application!

The **`sanitise_data/1`** function should be used _anywhere_ a `String` is accepted from a Client.

# Todo

Create the following "helper" function:

+ [x] **`sanitise_data/1`** should remove any undesirable markup and script tags/code from any data to prevent Cross Site Scripting (XSS).

If you are "unsure" what is required here, post a comment and I will add more _guidance_.
Start by scouring the Elixir ecosystem for how _other_ people are doing this in their Apps.
if your search is unfruitful, post a comment to that effect in this issue and we can "widen" the search e.g: https://stackoverflow.com/questions/129677/whats-the-best-method-for-sanitizing-user-input-with-php

**Comment by Danwhy** [comment]
https://github.com/rrrene/html_sanitize_ex has some sanitise functions ranging from completely stripping all html tags, to allowing only basic styling tags, or allowing html5 tags while still stripping malicious content.

**Comment by nelsonic** [comment]
@Danwhy good research. Please proceed with using this package for stripping HTML from the appropriate fields and XSS protection. thanks! ✨

**Comment by nelsonic** [comment]
https://github.com/dwyl/fields/blob/43f15171df363fa7f71ce14e36f44be41916b332/lib/html-body.ex#L22
implemented by @Danwhy ✅
