### ISSUE TITLE
Create :html-body field

### ISSUE THREAD

**Issue by Cleop** [dwyl/fields#27]
We need a field for text that allows the use of html for styling but that has been stripped of any harmful scripts that could harm a project. 

See: https://github.com/club-soda/club-soda-guide/issues/14#issuecomment-446906042

The `basic_html` fn in https://github.com/rrrene/html_sanitize_ex seems appropriate as it strips out everything other than the formatting.

**Comment by Cleop** [comment]
@nelsonic - I saw that you have already discussed sanitisation here: https://github.com/dwyl/fields/issues/19 and I wanted to check that you see this field type as useful? and a clear name?

**Comment by nelsonic** [comment]
@Cleop makes sense. 👍

**Comment by Cleop** [comment]
Closing as this has now been merged in and can be used
