### ISSUE TITLE
Fields.URL does not trim URL before running regex

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#33]
A url with a space at the end is being returned as invalid. 😞 
+ [x] trim url before running regex

**Comment by RobStallion** [comment]
I have just had this same issue with the validate email function. 

I think it may be worth checking all the validate functions to avoid this causing further issues in the future.

**Comment by nelsonic** [comment]
@RobStallion yeah, let's go through them all tomorrow. 👍

**Comment by nelsonic** [comment]
https://github.com/dwyl/fields/blob/43f15171df363fa7f71ce14e36f44be41916b332/lib/url.ex#L19

done. ✅
