### ISSUE TITLE
Update Ecto dependency

### ISSUE THREAD

**Issue by SimonLab** [dwyl/fields#46]
Installing the Fields package to a recent project creates a version conflict:
![image](https://user-images.githubusercontent.com/6057298/69648839-f8c9c180-1063-11ea-8def-62aad69dabbe.png)

I think updating the ecto version should fix this.

**Comment by nelsonic** [comment]
@SimonLab thanks for opening this issue and doing the update. 🥇

**Comment by nelsonic** [comment]
Updated via #47
