### ISSUE TITLE
Codecov: Add Test Coverage Tracking

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#50]
In our pursuit of being a ["High Performing Technology Org"](https://github.com/nelsonic/nelsonic.github.io/issues/758), we need to track test coverage in all our code.
So that we know when code is tested (_or not_) and can improve maintainability/reliability. 

# Todo

+ [x] Add `{:excoveralls, "~> 0.7.0", only: [:test, :dev]},` to **`deps`** in **`mix.exs`**
+ [x] Add `cover: ["coveralls.json"],  "cover.html": ["coveralls.html"]` to `aliases` section
+ [x] `test_coverage` entry in `project` section. see:
see: https://github.com/dwyl/phoenix-chat-example/blob/89d5d1127bafdcb9493c5dab060c291aa296f5e2/mix.exs#L14
+ [x] add codecov script to https://github.com/dwyl/elixir-auth-google/blob/master/.github/workflows/elixir.yml#L20

Examples we can follow:
+ https://github.com/dwyl/learn-elixir/tree/master/codecov_example
+ https://github.com/dwyl/phoenix-chat-example/blob/master/mix.exs
+ https://github.com/dwyl/phoenix-ecto-encryption-example/blob/master/mix.exs

**Comment by nelsonic** [comment]
Pleasantly pleased with the level of coverage _already_: 😍 
![image](https://user-images.githubusercontent.com/194400/69763454-2185b000-1165-11ea-9040-34ec5d2194bc.png)
it's a sign that _minimal_ code has been written. 🥇 
shouldn't take very long to write a few extra tests to get to 💯

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/69787021-81a34300-11b3-11ea-9a1a-cace3029e59c.png)

# 💯 

thanks to the great work done by @Danwhy, @Cleop, @RobStallion and @SimonLab 🎉 ❤️

**Comment by nelsonic** [comment]
PR #51 ready for review. 🔍 
CC: @SimonLab 🙏

**Comment by SimonLab** [comment]
Merged:
![image](https://user-images.githubusercontent.com/6057298/69797034-f0d66280-11c6-11ea-81ea-bcc393537204.png)

(the tests are running on master, I think that's why the badge is not properly displayed yet but I'll double check when it's finished)
