### ISSUE TITLE
Prepend key_id to ciphertext

### ISSUE THREAD

**Issue by SimonLab** [dwyl/fields#53]
I'm looking if it's possible to use the type map (instead of binary) here:
https://github.com/dwyl/fields/blob/06aa7469a0eebe8cbaacafd2361fcdb4ad76c489/lib/encrypted.ex#L15

to be able to store the token and the key index used to encrypt the token.

This idea comes from the research done on https://github.com/dwyl/app/issues/250

**Comment by nelsonic** [comment]
@SimonLab given that we are already storing other data prepended to the `ciphertext`, 
we could just prepend the **`key_id`** (_with a consistent fixed width of 4 bytes_) to the `ciphertext` 
see: https://github.com/dwyl/app/issues/250#issuecomment-559568401

We just need to test that we can _split_ the `key_id_str` from the concatenated/stored blob.

**Comment by nelsonic** [comment]
#55 merged. 👍 
Thanks @SimonLab
