### ISSUE TITLE
Add `input_type\0` function to all fields

### ISSUE THREAD

**Issue by SimonLab** [dwyl/fields#61]
The `input_type` function let the user know which type of form to used to represent a field.
At the moment only two fields are defining this function (HtmlBody and DescriptionPlaintextUnlimited).

We can define the `input_type` function in the other fields

**Comment by nelsonic** [comment]
@SimonLab can you please check if this still needs to be done when you look at #32 ? (thanks!)

**Comment by SimonLab** [comment]
The `input_type` function idea is from https://github.com/dwyl/fields/issues/20#issuecomment-442429971

It is used to know how to handle a field value in other program.
Unfortunately I don't remember the use case I had for creating the `input_type` value so I think we can close this issue for now and reopen it when necessary
