### ISSUE TITLE
wrong validation for emailHash field

### ISSUE THREAD

**Issue by SimonLab** [dwyl/fields#62]
The `EmailHash` field is using the `EmailPlainText` validation:
https://github.com/dwyl/fields/blob/6e61ceb214b349c76185cf22c3430c76626d3f31/lib/email_hash.ex#L20

which is using the `Validate.email` function:
https://github.com/dwyl/fields/blob/6e61ceb214b349c76185cf22c3430c76626d3f31/lib/email_plaintext.ex#L21

https://github.com/dwyl/fields/blob/6e61ceb214b349c76185cf22c3430c76626d3f31/lib/validate.ex#L20-L27

However a hash can't have an email format. We can instead use the `cast` function from `Hash`

**Comment by SimonLab** [comment]
I'm mistaken, the `cast` function is used to convert the original value which needs to be an email, so the validation is working correctly here.

**Comment by nelsonic** [comment]
Perhaps an inline comment could help the next person understand it better? 🤔
