### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Danwhy** [dwyl/fields#8]
Because this is not a full Phoenix app, it just uses Phoenix as a dependency (ie. We didn't run `mix phx.new`), the tests we would normally write are proving to be a little more difficult. We don't have access to modules like `ConnCase` which making testing Phoenix apps easy.

To help with this we could either:

__1.__ Create this as a new Phoenix app
or
__2.__ Create a new Phoenix app within the tests folder to use for testing.

My preference would be for number __2__, as we could then make sure in our mix.exs file using `elixirc_paths` that this code is only compiled in our tests. This would mean less overhead for apps that use this module when deploying.

If we were to make this a Phoenix app, we would be including a lot of code that will never be used apart from the tests (`endpoint.ex`, `repo.ex`, `router.ex`), it would be a lot less clear to people reading the code what is actually relevant, and it could provide some unseen problems when importing this module elsewhere.

@nelsonic your thoughts on this?

**Comment by Danwhy** [comment]
[drab](https://github.com/grych/drab) had the same issue, and went with an approach similar to __2__:
https://elixirforum.com/t/an-approach-to-functional-tests-phoenix-extension-library/3871

**Comment by nelsonic** [comment]
Hi Daniel, we _may_ be doing "too much work" for _this_ (Fields) module/package. 😉 
_Yes_, we need to _test_ what Fields is doing, but please see: https://github.com/dwyl/fields/issues/9

**Comment by nelsonic** [comment]
@Danwhy you mentioned https://github.com/grych/drab _above_ ⬆️ 
How much have you looked into it? Is it worth me investing a few hours to try it out? 🤔

**Comment by nelsonic** [comment]
Testing is adequately covered in this project. ✅ 
If we run into any issues we will open a more specific issue. 💭
